name: Continuous Integration and Delivery

on: [push]

permissions: write-all

env:
  IMAGE: ghcr.io/$(echo $GITHUB_REPOSITORY | tr '[A-Z]' '[a-z]')/my-website-docker:linux-built

jobs:
  deploy:
    name: Deploy to ECR
    runs-on: ubuntu-latest
    env:
      ECR_REPO_NAME: 714116641665.dkr.ecr.us-east-1.amazonaws.com/my-website
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Log in to GitHub Packages
        run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin ghcr.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull image
        run: |
          docker pull ${{ env.IMAGE }} || true
      - name: Build image
        run: |
          docker build \
            --cache-from ${{ env.IMAGE }} \
            --tag ${{ env.ECR_REPO_NAME }}:from-git \
            --file ./Dockerfile \
            "./project"
      - name: Log in to the AWS ECR
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 714116641665.dkr.ecr.us-east-1.amazonaws.com

      - name: Push to the registry
        run: docker push ${{env.ECR_REPO_NAME}}
